<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net462</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <Deterministic>True</Deterministic>
    <Version>0.0.1</Version>
    <Authors>lostmsu</Authors>
    <Description>Simple command-line tool that reads text aloud</Description>
    <PackageProjectUrl>https://github.com/lostmsu/Say</PackageProjectUrl>
    <RepositoryUrl>https://github.com/lostmsu/Say.git</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Say.Tests" />
    <Reference Include="System.Speech" />
  </ItemGroup>

</Project>
